### ISSUE TITLE
Untranslated string in Stats - Opportunity

### ISSUE THREAD

**Issue by flodolo** [mozilla/mrburns#101]
Go for example to https://webwewant.allizom.org/it/#stats-panel

Select "Opportunità", first paragraph on the right is untranslated, even if the .po file is completely translated (line 487)
http://viewvc.svn.mozilla.org/vc/projects/l10n-misc/trunk/glow2014/locale/it/LC_MESSAGES/django.po?revision=126663&view=markup

Is it a problem with the %%? I don't see it in the template
https://github.com/mozilla/mrburns/blob/master/mrburns/main/templates/stats.html#L401

If I change the string in the template, it's displayed localized but with the double %

![schermata 2014-04-22 alle 13 23 29](https://cloud.githubusercontent.com/assets/3644868/2764220/8ea797cc-ca10-11e3-8993-c974ac63e166.png)

**Comment by pmclanahan** [comment]
The strings look right in the .po file. The system doubles the percent signs because of the python-style replacements like `%(percentage)s`. In order to output a percent sign in a string like that, the percent must be `%%`, so the system extracts it like that.

I do see that there are issues in the german file however. So this may be remaining broken because the files aren't completing compilation due to a problem with `de`. The translation for `"%(percentage)s want a Web that keeps them in control of their lives online.\n"` is clearly incorrect. Looks like it was incorrectly pasted from the string below it. It doesn't have the right newlines nor does it contain the `%(percentage)s` place holder.

What should we do about that? Can I comment out that one for now, or will committing to SVN break the workflow with verbatim?

**Comment by koehlermichael** [comment]
Hi, do I understand correctly, that @flodolo has already fixed the issue for German? See http://viewvc.svn.mozilla.org/vc/projects/l10n-misc/trunk/glow2014/locale/de/LC_MESSAGES/django.po?r1=126894&r2=126893&pathrev=126894. If so, thanks a lot!

By the way, when I try to update the Glow translation on Verbatim, the following error occurs:

Failed to update from version control: [SVN] Subversion error running '['svn', 'update', u'/data/www/localize.mozilla.org/verbatim/pootle_env/Pootle/repos/glow2014/de']': Conflict discovered in '/data/www/localize.mozilla.org/verbatim/pootle_env/Pootle/repos/glow2014/de/LC_MESSAGES/django.po'. Select: (p) postpone, (df) diff-full, (e) edit, (mc) mine-conflict, (tc) theirs-conflict, (s) show all options: svn: Can't read stdin: End of file found

**Comment by flodolo** [comment]
Yes, I restored a previous version of the string. Can you try update from
vcs and then commit? If it doesn't work you should try to ping Matjaz.

**Comment by pmclanahan** [comment]
This is fixed. Closing. Please reopen if I'm wrong about that.
